// GENERATED FILE - do not edit by hand.
// Produced by scripts/build-translation.mjs from the public-domain KJV text.
// Regenerate with: npm run build:translation

/**
 * Static require map for the bundled KJV. Each loader is a thunk so that only
 * the books actually opened are parsed, rather than all 4.5 MB on launch.
 */
export const KJV_BOOK_LOADERS: Record<string, () => string[][]> = {
  'GEN': () => require('../../assets/translations/kjv/GEN.json') as string[][],
  'EXO': () => require('../../assets/translations/kjv/EXO.json') as string[][],
  'LEV': () => require('../../assets/translations/kjv/LEV.json') as string[][],
  'NUM': () => require('../../assets/translations/kjv/NUM.json') as string[][],
  'DEU': () => require('../../assets/translations/kjv/DEU.json') as string[][],
  'JOS': () => require('../../assets/translations/kjv/JOS.json') as string[][],
  'JDG': () => require('../../assets/translations/kjv/JDG.json') as string[][],
  'RUT': () => require('../../assets/translations/kjv/RUT.json') as string[][],
  '1SA': () => require('../../assets/translations/kjv/1SA.json') as string[][],
  '2SA': () => require('../../assets/translations/kjv/2SA.json') as string[][],
  '1KI': () => require('../../assets/translations/kjv/1KI.json') as string[][],
  '2KI': () => require('../../assets/translations/kjv/2KI.json') as string[][],
  '1CH': () => require('../../assets/translations/kjv/1CH.json') as string[][],
  '2CH': () => require('../../assets/translations/kjv/2CH.json') as string[][],
  'EZR': () => require('../../assets/translations/kjv/EZR.json') as string[][],
  'NEH': () => require('../../assets/translations/kjv/NEH.json') as string[][],
  'EST': () => require('../../assets/translations/kjv/EST.json') as string[][],
  'JOB': () => require('../../assets/translations/kjv/JOB.json') as string[][],
  'PSA': () => require('../../assets/translations/kjv/PSA.json') as string[][],
  'PRO': () => require('../../assets/translations/kjv/PRO.json') as string[][],
  'ECC': () => require('../../assets/translations/kjv/ECC.json') as string[][],
  'SNG': () => require('../../assets/translations/kjv/SNG.json') as string[][],
  'ISA': () => require('../../assets/translations/kjv/ISA.json') as string[][],
  'JER': () => require('../../assets/translations/kjv/JER.json') as string[][],
  'LAM': () => require('../../assets/translations/kjv/LAM.json') as string[][],
  'EZK': () => require('../../assets/translations/kjv/EZK.json') as string[][],
  'DAN': () => require('../../assets/translations/kjv/DAN.json') as string[][],
  'HOS': () => require('../../assets/translations/kjv/HOS.json') as string[][],
  'JOL': () => require('../../assets/translations/kjv/JOL.json') as string[][],
  'AMO': () => require('../../assets/translations/kjv/AMO.json') as string[][],
  'OBA': () => require('../../assets/translations/kjv/OBA.json') as string[][],
  'JON': () => require('../../assets/translations/kjv/JON.json') as string[][],
  'MIC': () => require('../../assets/translations/kjv/MIC.json') as string[][],
  'NAM': () => require('../../assets/translations/kjv/NAM.json') as string[][],
  'HAB': () => require('../../assets/translations/kjv/HAB.json') as string[][],
  'ZEP': () => require('../../assets/translations/kjv/ZEP.json') as string[][],
  'HAG': () => require('../../assets/translations/kjv/HAG.json') as string[][],
  'ZEC': () => require('../../assets/translations/kjv/ZEC.json') as string[][],
  'MAL': () => require('../../assets/translations/kjv/MAL.json') as string[][],
  'MAT': () => require('../../assets/translations/kjv/MAT.json') as string[][],
  'MRK': () => require('../../assets/translations/kjv/MRK.json') as string[][],
  'LUK': () => require('../../assets/translations/kjv/LUK.json') as string[][],
  'JHN': () => require('../../assets/translations/kjv/JHN.json') as string[][],
  'ACT': () => require('../../assets/translations/kjv/ACT.json') as string[][],
  'ROM': () => require('../../assets/translations/kjv/ROM.json') as string[][],
  '1CO': () => require('../../assets/translations/kjv/1CO.json') as string[][],
  '2CO': () => require('../../assets/translations/kjv/2CO.json') as string[][],
  'GAL': () => require('../../assets/translations/kjv/GAL.json') as string[][],
  'EPH': () => require('../../assets/translations/kjv/EPH.json') as string[][],
  'PHP': () => require('../../assets/translations/kjv/PHP.json') as string[][],
  'COL': () => require('../../assets/translations/kjv/COL.json') as string[][],
  '1TH': () => require('../../assets/translations/kjv/1TH.json') as string[][],
  '2TH': () => require('../../assets/translations/kjv/2TH.json') as string[][],
  '1TI': () => require('../../assets/translations/kjv/1TI.json') as string[][],
  '2TI': () => require('../../assets/translations/kjv/2TI.json') as string[][],
  'TIT': () => require('../../assets/translations/kjv/TIT.json') as string[][],
  'PHM': () => require('../../assets/translations/kjv/PHM.json') as string[][],
  'HEB': () => require('../../assets/translations/kjv/HEB.json') as string[][],
  'JAS': () => require('../../assets/translations/kjv/JAS.json') as string[][],
  '1PE': () => require('../../assets/translations/kjv/1PE.json') as string[][],
  '2PE': () => require('../../assets/translations/kjv/2PE.json') as string[][],
  '1JN': () => require('../../assets/translations/kjv/1JN.json') as string[][],
  '2JN': () => require('../../assets/translations/kjv/2JN.json') as string[][],
  '3JN': () => require('../../assets/translations/kjv/3JN.json') as string[][],
  'JUD': () => require('../../assets/translations/kjv/JUD.json') as string[][],
  'REV': () => require('../../assets/translations/kjv/REV.json') as string[][],
};
